In [65]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
import nltk

In [2]:
anime_df = pd.read_csv('Anime.csv')

In [3]:
anime_df

,ID,Title,Synonyms,Japanese,English,Synopsis,Type,Episodes,Status,Start_Aired,...,Themes,Demographics,Duration_Minutes,Rating,Score,Scored_Users,Ranked,Popularity,Members,Favorites
0,16498,Shingeki no Kyojin,"AoT, SnK",進撃の巨人,Attack on Titan,"Centuries ago, mankind was slaughtered to near...",TV,25.0,Finished Airing,"Apr 7, 2013",...,"Gore, Military, Survival",Shounen,24.0,R - 17+ (violence & profanity),8.531,519803.0,1002.0,1,3524109,155695
1,1535,Death Note,DN,デスノート,Death Note,"Brutal murders, petty thefts, and senseless vi...",TV,37.0,Finished Airing,"Oct 4, 2006",...,Psychological,Shounen,23.0,R - 17+ (violence & profanity),8.621,485487.0,732.0,2,3504535,159701
2,5114,Fullmetal Alchemist: Brotherhood,"Hagane no Renkinjutsushi Fullmetal Alchemist, ...",鋼の錬金術師 FULLMETAL ALCHEMIST,Fullmetal Alchemist Brotherhood,After a horrific alchemy experiment goes wrong...,TV,64.0,Finished Airing,"Apr 5, 2009",...,Military,Shounen,24.0,R - 17+ (violence & profanity),9.131,900398.0,12.0,3,2978455,207772
3,30276,One Punch Man,"One Punch-Man, One-Punch Man, OPM",ワンパンマン,One Punch Man,The seemingly unimpressive Saitama has a rathe...,TV,12.0,Finished Airing,"Oct 5, 2015",...,"Parody, Super Power",Seinen,24.0,R - 17+ (violence & profanity),8.511,19066.0,1112.0,4,2879907,59651
4,11757,Sword Art Online,"S.A.O, SAO",ソードアート・オンライン,Sword Art Online,Ever since the release of the innovative Nerve...,TV,25.0,Finished Airing,"Jul 8, 2012",...,"Love Polygon, Video Game",Unknown,23.0,PG-13 - Teens 13 or older,7.201,990254.0,29562.0,5,2813565,64997
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21455,45064,Xiao Gongzhu Ai Wei La Yu Shenmi Wangguo,Unknown,小公主艾薇拉与神秘王国,Princess and the Kingdom,Unknown,Movie,1.0,Finished Airing,"May 12, 2018",...,Unknown,Kids,78.0,G - All Ages,NaN,NaN,160892.0,21487,7,0
21456,45065,Xiao Gongzhu Ai Wei La Yu Shenmi Wangguo 2,Unknown,小公主艾薇拉与神秘王国2,Avera and the Mystical Kingdom 2,Unknown,Movie,1.0,Finished Airing,"Aug 22, 2020",...,Unknown,Kids,80.0,G - All Ages,NaN,NaN,160902.0,21488,6,0
21457,45059,Yongzhe Chuang Mo Cheng,Unknown,勇者闯魔城,Brave City,Unknown,Movie,1.0,Finished Airing,"Mar 16, 2018",...,Unknown,Unknown,80.0,G - All Ages,NaN,NaN,164032.0,21489,6,0
21458,45063,Yu Shen Chuan: Wangzhe Shaonian,Unknown,禹神传之王者少年,The Juvenile of King Yu,Unknown,Movie,1.0,Finished Airing,"Aug 15, 2018",...,Unknown,Unknown,90.0,G - All Ages,NaN,NaN,164462.0,21490,6,0
21459,45061,Konglong Wang,Unknown,恐龙王,Dino King,Unknown,Movie,1.0,Finished Airing,"Nov 10, 2018",...,Historical,Kids,95.0,G - All Ages,NaN,NaN,193202.0,21490,6,0

In [4]:
anime_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21460 entries, 0 to 21459
Data columns (total 28 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                21460 non-null  int64
 1   Title             21460 non-null  object
 2   Synonyms          21460 non-null  object
 3   Japanese          21460 non-null  object
 4   English           21460 non-null  object
 5   Synopsis          21460 non-null  object
 6   Type              21460 non-null  object
 7   Episodes          20913 non-null  float64
 8   Status            21460 non-null  object
 9   Start_Aired       21460 non-null  object
 10  End_Aired         21460 non-null  object
 11  Premiered         21460 non-null  object
 12  Broadcast         21460 non-null  object
 13  Producers         21460 non-null  object
 14  Licensors         21460 non-null  object
 15  Studios           21460 non-null  object
 16  Source            21460 non-null  object
 17  Genres            21460 non-null  object
 18  Themes            21460 non-null  object
 19  Demographics      21460 non-null  object
 20  Duration_Minutes  20861 non-null  float64
 21  Rating            21460 non-null  object
 22  Score             14562 non-null  float64
 23  Scored_Users      14562 non-null  float64
 24  Ranked            19536 non-null  float64
 25  Popularity        21460 non-null  int64
 26  Members           21460 non-null  int64
 27  Favorites         21460 non-null  int64
dtypes: float64(5), int64(4), object(19)
memory usage: 4.6+ MB

In [5]:
anime_df.isnull().sum()

ID                     0
Title                  0
Synonyms               0
Japanese               0
English                0
Synopsis               0
Type                   0
Episodes             547
Status                 0
Start_Aired            0
End_Aired              0
Premiered              0
Broadcast              0
Producers              0
Licensors              0
Studios                0
Source                 0
Genres                 0
Themes                 0
Demographics           0
Duration_Minutes     599
Rating                 0
Score               6898
Scored_Users        6898
Ranked              1924
Popularity             0
Members                0
Favorites              0
dtype: int64

In [6]:
selected_anime_df = anime_df[['ID','Title', 'Genres', 'Type', 'Themes', 'Synopsis' ,'Studios']]

In [7]:
selected_anime_df.head()

,ID,Title,Genres,Type,Themes,Synopsis,Studios
0,16498,Shingeki no Kyojin,"Action, Drama",TV,"Gore, Military, Survival","Centuries ago, mankind was slaughtered to near...",Wit Studio
1,1535,Death Note,"Supernatural, Suspense",TV,Psychological,"Brutal murders, petty thefts, and senseless vi...",Madhouse
2,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy",TV,Military,After a horrific alchemy experiment goes wrong...,Bones
3,30276,One Punch Man,"Action, Comedy",TV,"Parody, Super Power",The seemingly unimpressive Saitama has a rathe...,Madhouse
4,11757,Sword Art Online,"Action, Adventure, Fantasy, Romance",TV,"Love Polygon, Video Game",Ever since the release of the innovative Nerve...,A-1 Pictures

In [8]:
selected_anime_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21460 entries, 0 to 21459
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        21460 non-null  int64
 1   Title     21460 non-null  object
 2   Genres    21460 non-null  object
 3   Type      21460 non-null  object
 4   Themes    21460 non-null  object
 5   Synopsis  21460 non-null  object
 6   Studios   21460 non-null  object
dtypes: int64(1), object(6)
memory usage: 1.1+ MB

In [9]:
selected_anime_df.isnull().sum()

ID          0
Title       0
Genres      0
Type        0
Themes      0
Synopsis    0
Studios     0
dtype: int64

In [10]:
selected_anime_df.duplicated().sum()

0

In [11]:
selected_anime_df.iloc[0]['Genres']

'Action, Drama'

In [12]:
selected_anime_df['Synopsis'] = selected_anime_df['Synopsis'].apply(lambda x:x.split())

C:\Users\janak\AppData\Local\Temp\ipykernel_9088\607884942.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_anime_df['Synopsis'] = selected_anime_df['Synopsis'].apply(lambda x:x.split())

In [13]:
# removing mal written by text
# for i in range(len(selected_anime_df['Synopsis'])):
#     selected_anime_df['Synopsis'][i] = selected_anime_df['Synopsis'][i][0:-4]
selected_anime_df['Synopsis'][0]

['Centuries',
 'ago,',
 'mankind',
 'was',
 'slaughtered',
 'to',
 'near',
 'extinction',
 'by',
 'monstrous',
 'humanoid',
 'creatures',
 'called',
 'Titans,',
 'forcing',
 'humans',
 'to',
 'hide',
 'in',
 'fear',
 'behind',
 'enormous',
 'concentric',
 'walls.',
 'What',
 'makes',
 'these',
 'giants',
 'truly',
 'terrifying',
 'is',
 'that',
 'their',
 'taste',
 'for',
 'human',
 'flesh',
 'is',
 'not',
 'born',
 'out',
 'of',
 'hunger',
 'but',
 'what',
 'appears',
 'to',
 'be',
 'out',
 'of',
 'pleasure.',
 'To',
 'ensure',
 'their',
 'survival,',
 'the',
 'remnants',
 'of',
 'humanity',
 'began',
 'living',
 'within',
 'defensive',
 'barriers,',
 'resulting',
 'in',
 'one',
 'hundred',
 'years',
 'without',
 'a',
 'single',
 'titan',
 'encounter.',
 'However,',
 'that',
 'fragile',
 'calm',
 'is',
 'soon',
 'shattered',
 'when',
 'a',
 'colossal',
 'Titan',
 'manages',
 'to',
 'breach',
 'the',
 'supposedly',
 'impregnable',
 'outer',
 'wall,',
 'reigniting',
 'the',
 'fight',
 'for',
 'survival',
 'against',
 'the',
 'man-eating',
 'abominations.',
 'After',
 'witnessing',
 'a',
 'horrific',
 'personal',
 'loss',
 'at',
 'the',
 'hands',
 'of',
 'the',
 'invading',
 'creatures,',
 'Eren',
 'Yeager',
 'dedicates',
 'his',
 'life',
 'to',
 'their',
 'eradication',
 'by',
 'enlisting',
 'into',
 'the',
 'Survey',
 'Corps,',
 'an',
 'elite',
 'military',
 'unit',
 'that',
 'combats',
 'the',
 'merciless',
 'humanoids',
 'outside',
 'the',
 'protection',
 'of',
 'the',
 'walls.',
 'Eren,',
 'his',
 'adopted',
 'sister',
 'Mikasa',
 'Ackerman,',
 'and',
 'his',
 'childhood',
 'friend',
 'Armin',
 'Arlert',
 'join',
 'the',
 'brutal',
 'war',
 'against',
 'the',
 'Titans',
 'and',
 'race',
 'to',
 'discover',
 'a',
 'way',
 'of',
 'defeating',
 'them',
 'before',
 'the',
 'last',
 'walls',
 'are',
 'breached.',
 '[Written',
 'by',
 'MAL',
 'Rewrite]']

In [14]:
selected_anime_df['Genres'] = selected_anime_df['Genres'].apply(lambda x:x.split())

C:\Users\janak\AppData\Local\Temp\ipykernel_9088\2194521306.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_anime_df['Genres'] = selected_anime_df['Genres'].apply(lambda x:x.split())

In [15]:
selected_anime_df['Genres'][0]

['Action,', 'Drama']

In [16]:
selected_anime_df['Genres'] = selected_anime_df['Genres'].apply(lambda x:[i.replace(",", "") for i in x])

C:\Users\janak\AppData\Local\Temp\ipykernel_9088\1923918408.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_anime_df['Genres'] = selected_anime_df['Genres'].apply(lambda x:[i.replace(",", "") for i in x])

In [17]:
selected_anime_df['Genres'][0]

['Action', 'Drama']

In [18]:
selected_anime_df['Themes'] = selected_anime_df['Themes'].apply(lambda x:x.split())

C:\Users\janak\AppData\Local\Temp\ipykernel_9088\3773917316.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_anime_df['Themes'] = selected_anime_df['Themes'].apply(lambda x:x.split())

In [19]:
selected_anime_df['Themes'] = selected_anime_df['Themes'].apply(lambda x:[i.replace(",", "") for i in x])

C:\Users\janak\AppData\Local\Temp\ipykernel_9088\800963445.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_anime_df['Themes'] = selected_anime_df['Themes'].apply(lambda x:[i.replace(",", "") for i in x])

In [20]:
selected_anime_df['Themes'][0]

['Gore', 'Military', 'Survival']

In [21]:
selected_anime_df.head()

,ID,Title,Genres,Type,Themes,Synopsis,Studios
0,16498,Shingeki no Kyojin,"[Action, Drama]",TV,"[Gore, Military, Survival]","[Centuries, ago,, mankind, was, slaughtered, t...",Wit Studio
1,1535,Death Note,"[Supernatural, Suspense]",TV,[Psychological],"[Brutal, murders,, petty, thefts,, and, sensel...",Madhouse
2,5114,Fullmetal Alchemist: Brotherhood,"[Action, Adventure, Drama, Fantasy]",TV,[Military],"[After, a, horrific, alchemy, experiment, goes...",Bones
3,30276,One Punch Man,"[Action, Comedy]",TV,"[Parody, Super, Power]","[The, seemingly, unimpressive, Saitama, has, a...",Madhouse
4,11757,Sword Art Online,"[Action, Adventure, Fantasy, Romance]",TV,"[Love, Polygon, Video, Game]","[Ever, since, the, release, of, the, innovativ...",A-1 Pictures

In [22]:
selected_anime_df['tags'] = selected_anime_df['Synopsis']+selected_anime_df['Themes']+selected_anime_df['Genres']

C:\Users\janak\AppData\Local\Temp\ipykernel_9088\30050856.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  selected_anime_df['tags'] = selected_anime_df['Synopsis']+selected_anime_df['Themes']+selected_anime_df['Genres']

In [23]:
selected_anime_df.head()

,ID,Title,Genres,Type,Themes,Synopsis,Studios,tags
0,16498,Shingeki no Kyojin,"[Action, Drama]",TV,"[Gore, Military, Survival]","[Centuries, ago,, mankind, was, slaughtered, t...",Wit Studio,"[Centuries, ago,, mankind, was, slaughtered, t..."
1,1535,Death Note,"[Supernatural, Suspense]",TV,[Psychological],"[Brutal, murders,, petty, thefts,, and, sensel...",Madhouse,"[Brutal, murders,, petty, thefts,, and, sensel..."
2,5114,Fullmetal Alchemist: Brotherhood,"[Action, Adventure, Drama, Fantasy]",TV,[Military],"[After, a, horrific, alchemy, experiment, goes...",Bones,"[After, a, horrific, alchemy, experiment, goes..."
3,30276,One Punch Man,"[Action, Comedy]",TV,"[Parody, Super, Power]","[The, seemingly, unimpressive, Saitama, has, a...",Madhouse,"[The, seemingly, unimpressive, Saitama, has, a..."
4,11757,Sword Art Online,"[Action, Adventure, Fantasy, Romance]",TV,"[Love, Polygon, Video, Game]","[Ever, since, the, release, of, the, innovativ...",A-1 Pictures,"[Ever, since, the, release, of, the, innovativ..."

In [24]:
new_df = selected_anime_df[['tags', 'Title', 'ID']]

In [25]:
new_df

,tags,Title,ID
0,"[Centuries, ago,, mankind, was, slaughtered, t...",Shingeki no Kyojin,16498
1,"[Brutal, murders,, petty, thefts,, and, sensel...",Death Note,1535
2,"[After, a, horrific, alchemy, experiment, goes...",Fullmetal Alchemist: Brotherhood,5114
3,"[The, seemingly, unimpressive, Saitama, has, a...",One Punch Man,30276
4,"[Ever, since, the, release, of, the, innovativ...",Sword Art Online,11757
...,...,...,...
21455,"[Unknown, Unknown, Adventure, Fantasy]",Xiao Gongzhu Ai Wei La Yu Shenmi Wangguo,45064
21456,"[Unknown, Unknown, Adventure, Fantasy]",Xiao Gongzhu Ai Wei La Yu Shenmi Wangguo 2,45065
21457,"[Unknown, Unknown, Adventure, Comedy, Fantasy]",Yongzhe Chuang Mo Cheng,45059
21458,"[Unknown, Unknown, Adventure, Fantasy]",Yu Shen Chuan: Wangzhe Shaonian,45063
21459,"[Unknown, Historical, Adventure]",Konglong Wang,45061

In [26]:
new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

C:\Users\janak\AppData\Local\Temp\ipykernel_9088\3089450492.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

In [27]:
new_df

,tags,Title,ID
0,"Centuries ago, mankind was slaughtered to near...",Shingeki no Kyojin,16498
1,"Brutal murders, petty thefts, and senseless vi...",Death Note,1535
2,After a horrific alchemy experiment goes wrong...,Fullmetal Alchemist: Brotherhood,5114
3,The seemingly unimpressive Saitama has a rathe...,One Punch Man,30276
4,Ever since the release of the innovative Nerve...,Sword Art Online,11757
...,...,...,...
21455,Unknown Unknown Adventure Fantasy,Xiao Gongzhu Ai Wei La Yu Shenmi Wangguo,45064
21456,Unknown Unknown Adventure Fantasy,Xiao Gongzhu Ai Wei La Yu Shenmi Wangguo 2,45065
21457,Unknown Unknown Adventure Comedy Fantasy,Yongzhe Chuang Mo Cheng,45059
21458,Unknown Unknown Adventure Fantasy,Yu Shen Chuan: Wangzhe Shaonian,45063
21459,Unknown Historical Adventure,Konglong Wang,45061

In [28]:
new_df['tags'][0]

'Centuries ago, mankind was slaughtered to near extinction by monstrous humanoid creatures called Titans, forcing humans to hide in fear behind enormous concentric walls. What makes these giants truly terrifying is that their taste for human flesh is not born out of hunger but what appears to be out of pleasure. To ensure their survival, the remnants of humanity began living within defensive barriers, resulting in one hundred years without a single titan encounter. However, that fragile calm is soon shattered when a colossal Titan manages to breach the supposedly impregnable outer wall, reigniting the fight for survival against the man-eating abominations. After witnessing a horrific personal loss at the hands of the invading creatures, Eren Yeager dedicates his life to their eradication by enlisting into the Survey Corps, an elite military unit that combats the merciless humanoids outside the protection of the walls. Eren, his adopted sister Mikasa Ackerman, and his childhood friend Armin Arlert join the brutal war against the Titans and race to discover a way of defeating them before the last walls are breached. [Written by MAL Rewrite] Gore Military Survival Action Drama'

In [29]:
new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

C:\Users\janak\AppData\Local\Temp\ipykernel_9088\3214958533.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

In [30]:
new_df.head()

,tags,Title,ID
0,"centuries ago, mankind was slaughtered to near...",Shingeki no Kyojin,16498
1,"brutal murders, petty thefts, and senseless vi...",Death Note,1535
2,after a horrific alchemy experiment goes wrong...,Fullmetal Alchemist: Brotherhood,5114
3,the seemingly unimpressive saitama has a rathe...,One Punch Man,30276
4,ever since the release of the innovative nerve...,Sword Art Online,11757

In [31]:
cv = CountVectorizer(max_features=5000, stop_words='english')

In [32]:
cv.fit_transform(new_df['tags']).toarray().shape

(21460, 5000)

In [33]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [37]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [38]:
def stem(text):
    y = [ps.stem(i) for i in text.split()]
    return " ".join(y)

In [39]:
new_df['tags'] = new_df['tags'].apply(stem)

In [62]:
from sklearn.metrics.pairwise import cosine_similarity

In [63]:
# consumes memory 
similarity = cosine_similarity(vectors)

In [60]:
def recommend(anime):
    anime_index = new_df[new_df['Title']== anime].index[0]
    distances = similarity[anime_index]
    anime_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:6]
    for i in anime_list:
        print(new_df.iloc[i[0]].Title)

In [64]:
recommend("Death Note")

Death Note: Rewrite
Sekaikei Sekai Ron
Ghost Messenger
Da Yu Hai Tang (Movie)
Soul Eater

In [ ]:
# pickle tests below

In [44]:
# import pickle

In [45]:
# with open('similarity.uwu', 'wb') as file:
#     pickle.dump(similarity, file)

In [46]:
# with open('anime_df.uwu', 'wb') as file2:
#     pickle.dump(new_df, file2)

In [56]:
# with open('similarity.uwu', 'rb') as f2:
#     similiraty2 = pickle.load(f2)

In [58]:
# anime_index = new_df[new_df['Title']== 'Overflow'].index[0]
# distances = similiraty2[anime_index]
# anime_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:6]
# for i in anime_list:
#     print(new_df.iloc[i[0]].Title)

Bishoujo Animerama: Minami no Watashi no Heart ni Tacchi Shite...
Detective File 1: Kindan no Ai
Shikkoku no Shaga The Animation
Kimi Omou Koi
Shishunki Sex